base_config:
  model_name: "microsoft/Phi-3-mini-4k-instruct"
  num_train_samples: 10000
  num_val_samples: 1000

training_config:
  bf16: True
  do_eval: True  # Changed from False to True
  learning_rate: 5.0e-06
  log_level: "info"
  logging_steps: 20
  logging_strategy: "steps"
  lr_scheduler_type: "cosine"
  num_train_epochs: 1
  max_steps: -1
  output_dir: "./checkpoint_dir"
  overwrite_output_dir: True
  per_device_eval_batch_size: 4
  per_device_train_batch_size: 4
  remove_unused_columns: True
  save_steps: 100
  save_total_limit: 1
  seed: 0
  gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  gradient_accumulation_steps: 1
  warmup_ratio: 0.2
  report_to: "wandb"

peft_config:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules: "all-linear"
  modules_to_save: null

model_config:
  model_name: "microsoft/Phi-3-mini-4k-instruct"
  torch_dtype: torch.float16
  trust_remote_code: True
  use_cache: False
  attn_implementation: "eager"
  max_length: 2048

bnb_config:
  load_in_4bit: True
  bnb_4bit_compute_dtype: torch.float16
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: True

preprocessing:
  system_message: "You are General Knowledge Assistant. Answer the questions based on the provided information. Be succinct and use first-principles thinking to answer the questions."
  max_length: 2048  # Add this line